-- Setup account table
CREATE TABLE account (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  username TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
  updated_at TIMESTAMPTZ DEFAULT NOW() NOT NULL
);

-- Setup contact table
CREATE TABLE contact (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  name TEXT NOT NULL,
  nickname TEXT,
  job_title TEXT,
  organization TEXT,
  birthday DATE,
  relationship TEXT,
  notes TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
  updated_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
  account_id UUID REFERENCES account(id) NOT NULL,
  is_self BOOLEAN DEFAULT false NOT NULL
);

-- Setup category table
CREATE TABLE category (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  name TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
  updated_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
  account_id UUID REFERENCES account(id) NOT NULL
);

-- Setup contact_category table
CREATE TABLE contact_category (
  category_id UUID REFERENCES category(id) NOT NULL,
  contact_id UUID REFERENCES contact(id) NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
  updated_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
  PRIMARY KEY (category_id, contact_id)
);

-- Setup country table
CREATE TABLE country (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  name TEXT UNIQUE NOT NULL,
  alpha_2_code TEXT UNIQUE NOT NULL,
  alpha_3_code TEXT UNIQUE NOT NULL,
  calling_code TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
  updated_at TIMESTAMPTZ DEFAULT NOW() NOT NULL
);

-- Setup phone table
CREATE TABLE phone (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  number TEXT NOT NULL,
  label TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
  updated_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
  contact_id UUID REFERENCES contact(id) NOT NULL,
  country_id UUID REFERENCES country(id) NOT NULL
);

-- Setup address table
CREATE TABLE address (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  line_1 TEXT NOT NULL,
  line_2 TEXT,
  line_3 TEXT,
  postal_code TEXT NOT NULL,
  city TEXT NOT NULL,
  state TEXT NOT NULL,
  label TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
  updated_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
  contact_id UUID REFERENCES contact(id) NOT NULL,
  country_id UUID REFERENCES country(id) NOT NULL
);

-- Setup email table
CREATE TABLE email (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  address TEXT NOT NULL,
  label TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
  updated_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
  contact_id UUID REFERENCES contact(id) NOT NULL
);

-- Populate country table with official ISO data
INSERT INTO country (name, alpha_2_code, alpha_3_code, calling_code) VALUES
    ('Afghanistan','AF','AFG','93'),
    ('Albania','AL','ALB','355'),
    ('Algeria','DZ','DZA','213'),
    ('American Samoa','AS','ASM','1-684'),
    ('Andorra','AD','AND','376'),
    ('Angola','AO','AGO','244'),
    ('Anguilla','AI','AIA','1-264'),
    ('Antarctica','AQ','ATA','672'),
    ('Antigua & Barbuda','AG','ATG','1-268'),
    ('Argentina','AR','ARG','54'),
    ('Armenia','AM','ARM','374'),
    ('Aruba','AW','ABW','297'),
    ('Australia','AU','AUS','61'),
    ('Austria','AT','AUT','43'),
    ('Azerbaijan','AZ','AZE','994'),
    ('Bahamas','BS','BHS','1-242'),
    ('Bahrain','BH','BHR','973'),
    ('Bangladesh','BD','BGD','880'),
    ('Barbados','BB','BRB','1-246'),
    ('Belarus','BY','BLR','375'),
    ('Belgium','BE','BEL','32'),
    ('Belize','BZ','BLZ','501'),
    ('Benin','BJ','BEN','229'),
    ('Bermuda','BM','BMU','1-441'),
    ('Bhutan','BT','BTN','975'),
    ('Bolivia','BO','BOL','591'),
    ('Bosnia','BA','BIH','387'),
    ('Botswana','BW','BWA','267'),
    ('Bouvet Island','BV','BVT','47'),
    ('Brazil','BR','BRA','55'),
    ('British Indian Ocean Territory','IO','IOT','246'),
    ('British Virgin Islands','VG','VGB','1-284'),
    ('Brunei','BN','BRN','673'),
    ('Bulgaria','BG','BGR','359'),
    ('Burkina Faso','BF','BFA','226'),
    ('Burundi','BI','BDI','257'),
    ('Cambodia','KH','KHM','855'),
    ('Cameroon','CM','CMR','237'),
    ('Canada','CA','CAN','1'),
    ('Cape Verde','CV','CPV','238'),
    ('Caribbean Netherlands','BQ','BES','599'),
    ('Cayman Islands','KY','CYM','1-345'),
    ('Central African Republic','CF','CAF','236'),
    ('Chad','TD','TCD','235'),
    ('Chile','CL','CHL','56'),
    ('China','CN','CHN','86'),
    ('Christmas Island','CX','CXR','61'),
    ('Cocos (Keeling) Islands','CC','CCK','61'),
    ('Colombia','CO','COL','57'),
    ('Comoros','KM','COM','269'),
    ('Congo - Brazzaville','CG','COG','242'),
    ('Congo - Kinshasa','CD','COD','243'),
    ('Cook Islands','CK','COK','682'),
    ('Costa Rica','CR','CRI','506'),
    ('Croatia','HR','HRV','385'),
    ('Cuba','CU','CUB','53'),
    ('Curaçao','CW','CUW','599'),
    ('Cyprus','CY','CYP','357'),
    ('Czech Republic','CZ','CZE','420'),
    ('Côte d''Ivoire','CI','CIV','225'),
    ('Denmark','DK','DNK','45'),
    ('Djibouti','DJ','DJI','253'),
    ('Dominica','DM','DMA','1-767'),
    ('Dominican Republic','DO','DOM','1-809,1-829,1-849'),
    ('Ecuador','EC','ECU','593'),
    ('Egypt','EG','EGY','20'),
    ('El Salvador','SV','SLV','503'),
    ('Equatorial Guinea','GQ','GNQ','240'),
    ('Eritrea','ER','ERI','291'),
    ('Estonia','EE','EST','372'),
    ('Ethiopia','ET','ETH','251'),
    ('Falkland Islands','FK','FLK','500'),
    ('Faroe Islands','FO','FRO','298'),
    ('Fiji','FJ','FJI','679'),
    ('Finland','FI','FIN','358'),
    ('France','FR','FRA','33'),
    ('French Guiana','GF','GUF','594'),
    ('French Polynesia','PF','PYF','689'),
    ('French Southern Territories','TF','ATF','262'),
    ('Gabon','GA','GAB','241'),
    ('Gambia','GM','GMB','220'),
    ('Georgia','GE','GEO','995'),
    ('Germany','DE','DEU','49'),
    ('Ghana','GH','GHA','233'),
    ('Gibraltar','GI','GIB','350'),
    ('Greece','GR','GRC','30'),
    ('Greenland','GL','GRL','299'),
    ('Grenada','GD','GRD','1-473'),
    ('Guadeloupe','GP','GLP','590'),
    ('Guam','GU','GUM','1-671'),
    ('Guatemala','GT','GTM','502'),
    ('Guernsey','GG','GGY','44'),
    ('Guinea','GN','GIN','224'),
    ('Guinea-Bissau','GW','GNB','245'),
    ('Guyana','GY','GUY','592'),
    ('Haiti','HT','HTI','509'),
    ('Heard & McDonald Islands','HM','HMD','672'),
    ('Honduras','HN','HND','504'),
    ('Hong Kong','HK','HKG','852'),
    ('Hungary','HU','HUN','36'),
    ('Iceland','IS','ISL','354'),
    ('India','IN','IND','91'),
    ('Indonesia','ID','IDN','62'),
    ('Iran','IR','IRN','98'),
    ('Iraq','IQ','IRQ','964'),
    ('Ireland','IE','IRL','353'),
    ('Isle of Man','IM','IMN','44'),
    ('Israel','IL','ISR','972'),
    ('Italy','IT','ITA','39'),
    ('Jamaica','JM','JAM','1-876'),
    ('Japan','JP','JPN','81'),
    ('Jersey','JE','JEY','44'),
    ('Jordan','JO','JOR','962'),
    ('Kazakhstan','KZ','KAZ','7'),
    ('Kenya','KE','KEN','254'),
    ('Kiribati','KI','KIR','686'),
    ('Kuwait','KW','KWT','965'),
    ('Kyrgyzstan','KG','KGZ','996'),
    ('Laos','LA','LAO','856'),
    ('Latvia','LV','LVA','371'),
    ('Lebanon','LB','LBN','961'),
    ('Lesotho','LS','LSO','266'),
    ('Liberia','LR','LBR','231'),
    ('Libya','LY','LBY','218'),
    ('Liechtenstein','LI','LIE','423'),
    ('Lithuania','LT','LTU','370'),
    ('Luxembourg','LU','LUX','352'),
    ('Macau','MO','MAC','853'),
    ('Macedonia','MK','MKD','389'),
    ('Madagascar','MG','MDG','261'),
    ('Malawi','MW','MWI','265'),
    ('Malaysia','MY','MYS','60'),
    ('Maldives','MV','MDV','960'),
    ('Mali','ML','MLI','223'),
    ('Malta','MT','MLT','356'),
    ('Marshall Islands','MH','MHL','692'),
    ('Martinique','MQ','MTQ','596'),
    ('Mauritania','MR','MRT','222'),
    ('Mauritius','MU','MUS','230'),
    ('Mayotte','YT','MYT','262'),
    ('Mexico','MX','MEX','52'),
    ('Micronesia','FM','FSM','691'),
    ('Moldova','MD','MDA','373'),
    ('Monaco','MC','MCO','377'),
    ('Mongolia','MN','MNG','976'),
    ('Montenegro','ME','MNE','382'),
    ('Montserrat','MS','MSR','1-664'),
    ('Morocco','MA','MAR','212'),
    ('Mozambique','MZ','MOZ','258'),
    ('Myanmar','MM','MMR','95'),
    ('Namibia','NA','NAM','264'),
    ('Nauru','NR','NRU','674'),
    ('Nepal','NP','NPL','977'),
    ('Netherlands','NL','NLD','31'),
    ('New Caledonia','NC','NCL','687'),
    ('New Zealand','NZ','NZL','64'),
    ('Nicaragua','NI','NIC','505'),
    ('Niger','NE','NER','227'),
    ('Nigeria','NG','NGA','234'),
    ('Niue','NU','NIU','683'),
    ('Norfolk Island','NF','NFK','672'),
    ('North Korea','KP','PRK','850'),
    ('Northern Mariana Islands','MP','MNP','1-670'),
    ('Norway','NO','NOR','47'),
    ('Oman','OM','OMN','968'),
    ('Pakistan','PK','PAK','92'),
    ('Palau','PW','PLW','680'),
    ('Palestine','PS','PSE','970'),
    ('Panama','PA','PAN','507'),
    ('Papua New Guinea','PG','PNG','675'),
    ('Paraguay','PY','PRY','595'),
    ('Peru','PE','PER','51'),
    ('Philippines','PH','PHL','63'),
    ('Pitcairn Islands','PN','PCN','870'),
    ('Poland','PL','POL','48'),
    ('Portugal','PT','PRT','351'),
    ('Puerto Rico','PR','PRI','1'),
    ('Qatar','QA','QAT','974'),
    ('Romania','RO','ROU','40'),
    ('Russia','RU','RUS','7'),
    ('Rwanda','RW','RWA','250'),
    ('Réunion','RE','REU','262'),
    ('Samoa','WS','WSM','685'),
    ('San Marino','SM','SMR','378'),
    ('Saudi Arabia','SA','SAU','966'),
    ('Senegal','SN','SEN','221'),
    ('Serbia','RS','SRB','381'),
    ('Seychelles','SC','SYC','248'),
    ('Sierra Leone','SL','SLE','232'),
    ('Singapore','SG','SGP','65'),
    ('Sint Maarten','SX','SXM','1-721'),
    ('Slovakia','SK','SVK','421'),
    ('Slovenia','SI','SVN','386'),
    ('Solomon Islands','SB','SLB','677'),
    ('Somalia','SO','SOM','252'),
    ('South Africa','ZA','ZAF','27'),
    ('South Georgia & South Sandwich Islands','GS','SGS','500'),
    ('South Korea','KR','KOR','82'),
    ('South Sudan','SS','SSD','211'),
    ('Spain','ES','ESP','34'),
    ('Sri Lanka','LK','LKA','94'),
    ('Saint Barthélemy','BL','BLM','590'),
    ('St. Helena','SH','SHN','290'),
    ('St. Kitts & Nevis','KN','KNA','1-869'),
    ('St. Lucia','LC','LCA','1-758'),
    ('St. Martin','MF','MAF','590'),
    ('St. Pierre & Miquelon','PM','SPM','508'),
    ('St. Vincent & Grenadines','VC','VCT','1-784'),
    ('Sudan','SD','SDN','249'),
    ('Suriname','SR','SUR','597'),
    ('Svalbard & Jan Mayen','SJ','SJM','47'),
    ('Swaziland','SZ','SWZ','268'),
    ('Sweden','SE','SWE','46'),
    ('Switzerland','CH','CHE','41'),
    ('Syria','SY','SYR','963'),
    ('Sao Tome and Principe','ST','STP','239'),
    ('Taiwan','TW','TWN','886'),
    ('Tajikistan','TJ','TJK','992'),
    ('Tanzania','TZ','TZA','255'),
    ('Thailand','TH','THA','66'),z
    ('Timor-Leste','TL','TLS','670'),
    ('Togo','TG','TGO','228'),
    ('Tokelau','TK','TKL','690'),
    ('Tonga','TO','TON','676'),
    ('Trinidad & Tobago','TT','TTO','1-868'),
    ('Tunisia','TN','TUN','216'),
    ('Turkey','TR','TUR','90'),
    ('Turkmenistan','TM','TKM','993'),
    ('Turks & Caicos Islands','TC','TCA','1-649'),
    ('Tuvalu','TV','TUV','688'),
    ('U.S. Outlying Islands','UM','UMI','1'),
    ('U.S. Virgin Islands','VI','VIR','1-340'),
    ('UK','GB','GBR','44'),
    ('US','US','USA','1'),
    ('Uganda','UG','UGA','256'),
    ('Ukraine','UA','UKR','380'),
    ('United Arab Emirates','AE','ARE','971'),
    ('Uruguay','UY','URY','598'),
    ('Uzbekistan','UZ','UZB','998'),
    ('Vanuatu','VU','VUT','678'),
    ('Vatican City','VA','VAT','39-06'),
    ('Venezuela','VE','VEN','58'),
    ('Vietnam','VN','VNM','84'),
    ('Wallis & Futuna','WF','WLF','681'),
    ('Western Sahara','EH','ESH','212'),
    ('Yemen','YE','YEM','967'),
    ('Zambia','ZM','ZMB','260'),
    ('Zimbabwe','ZW','ZWE','263'),
    ('Åland Islands','AX','ALA','358');
